### ISSUE TITLE
Add Repo Topics

### ISSUE THREAD

**Issue by jbjonesjr** [LLNL/scraper#1]
It would be awesome if this repo could include a `code-gov` topic to make it easily discoverable along other code.gov related utilities on GitHub.com.

Topics are now an even more prominent part of the discovery experience of GitHub.com (https://github.com/topics), and are being used to help users discover projects they may be interested in (https://github.com/updates). Creating a centralized place for code.gov repositories may also help in reducing duplication of effort as well.

Also, that would then make them more easily searchable on https://code.gov... how meta.

**Comment by IanLee1521** [comment]
Awesome! Is there any sort of central list for standard topics? If not, it might be worth making one, perhaps in https://github.com/government/best-practices ?

**Comment by IanLee1521** [comment]
Added, thanks @jbjonesjr

**Comment by IanLee1521** [comment]
This comment (https://github.com/government/best-practices/issues/152#issuecomment-323137538) and this tweet (https://twitter.com/benbalter/status/826544974946721794) by @benbalter also seem applicable here.

**Comment by jbjonesjr** [comment]
Yeah, I think in general code.gov is going to be the ultimate discovery tool ( ;) ), but until then, i'd love to get people to auto-tag their repos with some sort of govt id (or multiple things: `government-research`, `government-energy-lab`, etc).

I'm still also manually curating this: https://github.com/collections/government, but that can't be an EVERYTHING list.

**Comment by IanLee1521** [comment]
Nod nod.

Hey how possible would it be to get the LLNL Software Catalog (https://software.llnl.gov) highlighted there too? Of note is our exploration page (https://software.llnl.gov/explore) and the FedScoop article that was written about that work and the GitHub Universe talk last year (https://www.fedscoop.com/livermore-national-laboratory-open-source-github-2016/)
