### ISSUE TITLE
TFS support

### ISSUE THREAD

**Issue by leebrian** [LLNL/scraper#23]
CDC has about a third of our internal repos using TFS, so having TFS in addition to GitHub, GitLab, and BitBucket would help us better inventory our TFS-hosted projects.

While, I'll eventually build this out, I wanted to create a ticket and reference it on code.gov's https://code.gov/#!/open-tasks. I felt a bit uncomfortable adding an item on code.gov for CDC request to an LLNL project repo without checking here first.

**Comment by IanLee1521** [comment]
Thanks @leebrian for the report!

Would you be willing / able to explore adding support for and submitting a pull request?

**Comment by leebrian** [comment]
@IanLee1521 

Would you please add the "help wanted" and "code.gov" labels so code.gov picks up this issue?

**Comment by IanLee1521** [comment]
@leebrian -- done.

**Comment by IanLee1521** [comment]
@leebrian did we ever get a pull request going to merge this up to master?

**Comment by leebrian** [comment]
No, we are testing it internally from an internal fork. The last GSA call had a few other folks who were interested in testing, so I will rework it to a proper fork on cdcgov and send a draft pull request for visibility. Maybe this week unless you'd like it sooner.

**Comment by IanLee1521** [comment]
At your convenience. No rush from my end. Cheers!

**Comment by IanLee1521** [comment]
Closed with https://github.com/LLNL/scraper/pull/28

**Comment by IanLee1521** [comment]
Released v0.7.0 to PyPI: https://pypi.org/project/llnl-scraper/
