### ISSUE TITLE
Missing Dependency in Requires

### ISSUE THREAD

**Issue by LRWeber** [LLNL/scraper#39]
The [requirements](https://github.com/LLNL/scraper/blob/49bad7c09677b5c45ddf22b3ccd2444bf5c1322e/requirements/production.txt) do not include `pytz`, which is required for [`scraper/github/queryManager.py`](https://github.com/LLNL/scraper/blob/49bad7c09677b5c45ddf22b3ccd2444bf5c1322e/scraper/github/queryManager.py).

**Comment by IanLee1521** [comment]
Hmm... is that not a requirement in scraper? We should put the dependency where it’s really needed if we can.

**Comment by LRWeber** [comment]
Apparently it _was_ included at one point.
https://github.com/LLNL/scraper/commit/2eba93d69b7d0f1da635ea5e25ac9badbb3b9f65

Then it got removed somewhere down the line.
