### ISSUE TITLE
Convert to using GraphQL for GitHub API

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/scraper#4]
It would be better to convert our REST calls to the GitHub API over to using the GraphQL endpoints.

Apparently this is emoting that now has a python package we may be able to use:

- https://github.com/graphcool/python-graphql-client

Example:

- https://github.com/GSA/code-gov-stats-jupyter-notebook/blob/master/code-gov-github-stats.ipynb

**Comment by LRWeber** [comment]
GraphQL functionality has been added via #7
