### ISSUE TITLE
Cocomo url not working

### ISSUE THREAD

**Issue by lbeaufort** [LLNL/scraper#55]
Hi! 👋 thanks for providing this great resource!

The Cocomo link here: https://github.com/LLNL/scraper/blob/84545d6730c411957eed7c2b028ea718aaa90890/scraper/util.py#L166
 doesn't seem to work anymore.

```
curl "https://csse.usc.edu/tools/cocomoii.php"
curl: (7) Failed to connect to csse.usc.edu port 443: Operation timed out
```

[The USC site](http://csse.usc.edu/tools) links to http://softwarecost.org/tools/COCOMO/ and the scraper seems to work when I update `cocomo_url` to this softwarecost.org URL. Do you think the link be updated? Thanks!

**Comment by IanLee1521** [comment]
Thanks @lbeaufort ! 

This is the second time they've changed the URL on us. :)

I don't suppose you're willing to submit the PR to fix the URL are you?

**Comment by lbeaufort** [comment]
I'd be happy to, I'll do that today :)
